# 1. Configurações de Conexão com o Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/loja_william?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# 2. Configurações do Hibernate
# 'update' faz o Spring olhar para as suas tabelas sem apagar o que você já fez lá no MySQL
spring.jpa.hibernate.ddl-auto=update

# 3. Para vermos o Spring trabalhando nos bastidores
spring.jpa.show-sql=true